### ISSUE TITLE
clean_P removes letters from variable names 

### ISSUE THREAD

**Issue by SchollJ** [mwheymans/miceafter#1]
I posted an error I got here: https://stackoverflow.com/questions/75765704/mice-pooling-glm-error-for-some-models-but-not-others-from-same-data-set/75765855#75765855
Summary: for some variable names as predicted variables, the pool command gave an error. I tracked this down to the clean_P command changing the variable name.
Here is an example that worked: sticsa.trait.somatic.predicted.H2B
And here one that didn't work: shaps.predicted.H3Bi
For the one that didn't work, the output of clean_P(names(imp_dat[[1]]) was shaps.predicted.HBi

**Comment by mwheymans** [comment]
Clean_P removes numbers from variable names to detect spline variables with knot numbers and is called by e.g. pool_glm. To pool models it is required to use unique variable names without numbers, so not bmi12, age36, but just bmi, age. Than the function can be used for all kind of variables, i.e. categorical, splines, etc. .
